apiVersion: v1
kind: Service
metadata:
  name: alpha
spec:
  ports:
  - port: 8080
    targetPort: 5678
  type: ClusterIP
  selector:
    app: alpha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
spec:
  selector:
    matchLabels:
      app: alpha
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: alpha
        version: "1.0"
    spec:
      containers:
      - name: alpha
        image: hashicorp/http-echo
        args:
        - "-text=Alpha v1"
        ports:
        - containerPort: 5678
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: alpha
spec:
  parentRefs:
  - name: shared-gateway
    namespace: infra-ns
  rules:
  - matches:
    - path:
        value: /alpha
    backendRefs:
    - name: echo
      port: 8080
